linters:
  enable:
    # Default linters, which we make explicit.
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Optional linters, which we choose to apply additionally.
    - bodyclose
    - bidichk
    - containedctx
    - contextcheck
    - dupl
    - errname
    - errorlint
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - gofmt
    - gosec
    - gosimple
    - gofumpt
    - lll
    - misspell
    - nestif
    - noctx
    - prealloc
    - reassign
    - revive
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
    - revive

    # To be evaluated
#    - gochecknoglobals    # Check that no global variables exist
#    - ireturn             # Accept Interfaces, Return Concrete Types.

linters-settings:
  revive:
    rules:
      - name: exported

  gci:
    sections:
      - standard
      - prefix(github.com/e-identification/bankid-go)
      - default
    custom-order: true

issues:
  include:
    - "EXC0012" # revive exported comments
  exclude-rules:
    - linters:
        - lll
      source: "^// "

run:
  go: '1.20'
  skip-dirs:
    - docs
